<div class="jumbotron">
    <h1>OAuth2 Client Provider Testing</h1>
    <h2><?= $provider; ?></h2>

    <?php if ($valid) { ?>
        <p class="alert alert-success">PASSED</p>
        <pre><?= print_r($token, true); ?></pre>
    <?php } ?>

    <p>
        <?php foreach ($providers as $provider) { ?>
        <a class="btn btn-default btn-large" href="/init?run=<?= $provider; ?>"><?= $provider; ?></a> &nbsp;
        <?php } ?>
    </p>
</div>

