<div class="jumbotron">
    <h1>OAuth2 Client Provider Testing</h1>
    <p>
        This tool tests the provider for league/oauth2-client.  You may click on a provider 
        to run it's OAuth2 process.
    </p>

    <p>
        <?php foreach ($providers as $provider) { ?>
        <a class="btn btn-default btn-large" href="/init?run=<?= $provider; ?>"><?= $provider; ?></a> &nbsp;
        <?php } ?>
    </p>
</div>

